### ISSUE TITLE
Custom attribute to ignore inlining

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#10]

**Comment by kontur** [comment]
This feature would be great. Here's a real world use case I found where this would be very useful:

I am Inlining the css of an html email. I have some elements (e.g. images) that I'd like to swap with `@media (prefers-color-scheme: dark )` — I could inline _most_ CSS for these images, but the `display: block|none` to toggle display for default/dark mode will not work with inlined styles.
