### ISSUE TITLE
Stylesheet incorrectly overrides `style` attribute values

### ISSUE THREAD

**Issue by tomi-bigpi** [Stranger6667/css-inline#113]
When an element has both a `class` attribute and a `style` attribute, styles from the stylesheet are merged into the destination `style` attribute. However, existing values in the element's `style` are overwritten by the values from the stylesheet whereas existing `style` attribute values should override any values in the stylesheet. This issue results in incorrect styles being applied on elements.

## Sample Jest test
```javascript
import { inline } from "css-inline";

describe("css-inline", () => {
  it.only("correctly allows style tag to override stylesheet", () => {
    const document =
`<html>
  <head><style>p.MsoNormal {margin-left:0in;font-size:14px;font-family:Arial;}</style></head>
  <body><p class=MsoNormal style='margin-left:.25in;font-family:Calibri;'>Some text goes here</p></body>
</html>`;

    const expected =
`<html><head></head>
  <body><p class="MsoNormal" style="margin-left:.25in;font-family:Calibri;font-size:14px;">Some text goes here</p></body>
</html>`;

    expect(inline(document, { inline_style_tags: true, remove_style_tags: true })).toEqual(expected);
  });
});
```

## Expected result (`margin-left` should stay as `.25in` and `font-family` should stay as `Calibri`):
```html
<html><head></head>
<body><p class="MsoNormal" style="margin-left:.25in;font-family:Calibri;font-size:14px;">Some text goes here</p></body>
</html>
```

## Actual result (stylesheet overrides all existing values in `style` attribute):
```html
<html><head></head>
<body><p class="MsoNormal" style="margin-left:0in;font-family:Arial;font-size:14px;">Some text goes here</p>
</body>
</html>
```

**Comment by Stranger6667** [comment]
Hi @tomi-bigpi 

Thanks for reporting! I'll check this tomorrow

**Comment by Stranger6667** [comment]
An extra thank you for the detailed description & a test case! :)

**Comment by tomi-bigpi** [comment]
@Stranger6667 Just pulled down version 0.7.2 and everything looks great!

Thanks for the super-fast turnaround on this!!

//TB

**Comment by Stranger6667** [comment]
You are very welcome! :)
