### ISSUE TITLE
Minimize inlined css

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#12]
Now we have some extra spaces that are not needed. `;` in the end, is also optional

**Comment by mrdziuban** [comment]
Hey @Stranger6667, was this implemented? I'm seeing spaces between CSS properties and values and semicolons at the end of HTML `style` attributes, wondering if there's a way to remove them. Thanks in advance!

**Comment by Stranger6667** [comment]
Hi! I think originally I pushed some changes to remove the spaces and closed this issue. Later on, I noted that removing them added some extra cost, so I adjusted the logic to avoid it and completely forgot to revisit this issue.

It could be done, surely. Maybe another config option could be added to control it

**Comment by mrdziuban** [comment]
Thanks for the quick response! I can take a look at adding that option
