### ISSUE TITLE
Do not encode double quotes from `font-family` as `"&quot;"

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#129]
From [W3Schools](https://www.w3schools.com/cssref/pr_font_font-family.asp):
> Note: If a font name contains white-space, it must be quoted. Single quotes must be used when using the "style" attribute in HTML.

Currently `h1 { font-family: "Open Sans", sans-serif; }` will be inlined as `style="font-family: &quot;Open Sans&quot;, sans-serif;"`

**Comment by Elendiar** [comment]
<img width="939" alt="image" src="https://github.com/Stranger6667/css-inline/assets/3886001/bb957edb-747a-4d23-a94f-b88ff784a56f">

that's probably why this happened to me with bootstrap (

**Comment by Stranger6667** [comment]
It looks like it is not in font-family - probably we need to process all attributes this way, not just font-family
