### ISSUE TITLE
mac osx arm64 build

### ISSUE THREAD

**Issue by xorduna** [Stranger6667/css-inline#140]
Hi! I just compiled css-inline python binding for mac osx arm64 without any problem and it works perfetly. Is there any way I cap help uploading this build as a wheel for other users?

I tried to execute `python3 -m build` but I got this error

`error: failed to get `css-inline` as a dependency of package `css-inline-python v0.8.1 (/private/var/folders/cn/qmc8lb9j5ddclqxj073wdky40000gn/T/build-via-sdist-gffl6klk/css_inline-0.8.1)`

Thanks!

**Comment by Stranger6667** [comment]
Hey! Sorry for the delay. `css-inline==0.8.5` should properly support universal wheels for Mac OS, so it should not be a problem anymore :) Feel free to reopen this issue if it doesn't work
