### ISSUE TITLE
Don't convert HTML Entities to Unicode.

### ISSUE THREAD

**Issue by dkechag** [Stranger6667/css-inline#141]
I've been using an old Perl css-inliner, which is quite good, but very, very slow (yes, I mean very slow even for pure Perl). I was happy to see this Rust-powered solution, and it is indeed over 100x faster, but has a "feature" that sort of breaks it for me and I don't get the reason. So, given input:
```
<html>
<head><meta content="text/html; charset=iso-8859-1" http-equiv="Content-Type"></head>
<body>Here&rsquo;s Johnny</body>
</html>
```
I get:
```
<html><head><meta content="text/html; charset=iso-8859-1" http-equiv="Content-Type"></head>
<body>Here’s Johnny

</body></html>
```
Which comes up as `Hereâ€™s Johnny` on the browser.
Now, one could say why use the right single quote (although it is very common for typography reasons in place of apostrophe), but that was just an example, even things like `&pound;` get translated to 0xC2 0xA3, which looks quite bad unless your charset is UTF-8. Which is not great if you are trying to inline various things you did not create with that limitation in mind.
I looked in the python wrapper code as I went through that, and I see it is not doing anything special apart from calling the Rust package, and looking into the Rust doc I don't see any control (or mention) of this behaviour, so the issue might be with the Servo components and not with `css-inline` technically, but I thought I'd ask in case I might be missing something.

**Comment by Stranger6667** [comment]
Hi!

Indeed, it comes from the `html5ever` implementation and I don't see a way to control it. It looks like it follows the [tokenization flow](https://www.w3.org/TR/2011/WD-html5-20110525/tokenization.html#consume-a-character-reference) for HTML5 which states:

> Return one or two character tokens for the character(s) corresponding to the character reference name (as given by the second column of the [named character references](https://www.w3.org/TR/2011/WD-html5-20110525/named-character-references.html#named-character-references) table).

So, it is parsed as `’`. Then, it is [serialized as is](https://github.com/servo/html5ever/blob/6a8ce7de9070f670b661ca644056166ce1ac0244/html5ever/src/serialize/mod.rs#L113) and I assume that it is allowed by the spec (though, I didn't dig deep enough to find the exact definition). 

This is my current understanding of the situation. Though, `html5ever` might not support / care about encodings other than UTF8 and ignore certain cases. The `css-inline` crate relies on `html5ever` behavior and it is not likely to change in the near future.

**Comment by Stranger6667** [comment]
I added a note on this behavior to the README file and going to close this issue as I don't think there are any other action items.
