### ISSUE TITLE
css-inline does not follow cascade/specificity rules

### ISSUE THREAD

**Issue by dkechag** [Stranger6667/css-inline#142]
I noticed that for complex html, the css-inliner output often does not look the same as the input on a browser. Digging into it I can see the issue, so here is a simple test case: Given this `test.html`:
```
<html>
  <head>
    <style type='text/css'>
table, tr {padding: 0;}
table.content {padding-top: 24px;}
    </style>
  </head>
  <body>
      <table class="content">
        <tr><td>Content</td></tr>
    </table>
  </body>
</html>
```
Running `css-inline test.html` repeatedly will randomly give one of the two results below:
```
<html><head>
    <style type="text/css">
table, tr {padding: 0;}
table.content {padding-top: 24px;}
    </style>
  </head>
  <body>
      <table class="content" style="padding-top: 24px;padding: 0;">
        <tbody><tr style="padding: 0;"><td>Content</td></tr>
    </tbody></table>

</body></html>
```
or
```
<html><head>
    <style type="text/css">
table, tr {padding: 0;}
table.content {padding-top: 24px;}
    </style>
  </head>
  <body>
      <table class="content" style="padding: 0;padding-top: 24px;">
        <tbody><tr style="padding: 0;"><td>Content</td></tr>
    </tbody></table>

</body></html>
```
These are NOT equivalent, the `padding-top` will be 0 in the first case, 24 in the latter (which should be the correct one I believe), yet `css-inliner` apparently considers them the same and outputs one or the other at random.

rustc 1.59.0, css-inline 0.8.0

**Comment by ahmadjubair33** [comment]
Hi @dkechag Can I try to solve this issue? if yes please assign me.

**Comment by Stranger6667** [comment]
Hi @dkechag 

Thank you for reporting! Indeed, we use `HashMap` that doesn't guarantee iteration order, therefore the output differs in different runs. A possible solution is to switch to `indexmap` instead. At the moment I don't have the bandwidth to work on this myself - maybe in a few weeks. But I'll definitely review any PRs to solve this.

**Comment by Stranger6667** [comment]
> which should be the correct one I believe

Yes, it has higher specificity

**Comment by dkechag** [comment]
> Hi @dkechag Can I try to solve this issue? if yes please assign me.

Not my project to be able to assign people, but why not give it a try and push a PR?
