### ISSUE TITLE
[Python] Distribute typing information

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#167]
It would be useful if Python artifacts will have type stubs. At the moment, not all editors can utilize docstrings (i.e. some PyCharm versions use them) to get the typing info and it is definitely not enough for a pleasant developer experience.

**Comment by messense** [comment]
While we don't have auto-generated typing information from pyo3 yet, you can just add a handwritten `css_inline.pyi` file to `bindings/python` and `maturin` will package it automatically.

**Comment by Stranger6667** [comment]
@messense thanks!
