### ISSUE TITLE
Add support for local base url

### ISSUE THREAD

**Issue by lesleyxyz** [Stranger6667/css-inline#171]
Currently, when you supply a local directory for base_url it gives the following error:
```
Traceback (most recent call last):
  File "/redacted.py", line 181, in build_html_templates
    inlined = css_inline.inline(f.read(), base_url="/my/css/folder/")
ValueError: relative URL without a base
```

With base_url `file://my/css/folder/` it doesn't throw an error, but doesn't do any inlining

Am I doing something wrong or is this not supported at the moment?

**Comment by Stranger6667** [comment]
Hi @lesleyxyz

Thank you for opening this issue! Indeed, this one is missing - `base_url` only works for network stuff. I think we need to support the "file" scheme, so something like this would work (note three slashes):

```
file:///my/css/folder/
```

**Comment by Stranger6667** [comment]
#172 adds support for this

**Comment by lesleyxyz** [comment]
Damn that was quick, thank you so much!

**Comment by Stranger6667** [comment]
You're very welcome :)

**Comment by Stranger6667** [comment]
The change is released in [0.8.6](https://pypi.org/project/css-inline/0.8.6/)

**Comment by Stranger6667** [comment]
Let me know if it would not work for your use case

**Comment by lesleyxyz** [comment]
Just tested it today and working perfectly, so thank you!
