### ISSUE TITLE
add support for replacing custom properties (CSS variables) with inline values

### ISSUE THREAD

**Issue by larrybotha** [Stranger6667/css-inline#180]
In Gmail, and likely in other email clients, a number of CSS 3 properties aren't supported, including [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

Currently the custom properties are inlined as-is. I'm not sure if this is a bug or not, as there may be a valid use-cases for retaining the custom properties.

This is likely safer to implement as a configuration option to inline the custom properties.

As an example:

**Input:**

```css
:root {
  --clr: red;
}

.red {
  color: var(--clr);
}
```

```html
<div class="red"></div>
```

**After inlining**:

```html
<div style="color:  red;"></div>
```

Currently, `css-inline` produces the following:

```html
<div style="color:  var(--clr);"></div>
```

There are a couple cases to handle, with the most top of mind being:

- unable to resolve a custom property
- handling fallback values
- traversing up the cascade for resolution, as custom properties can be scoped within classes, not only in `:root`

Would love to tackle this, as I'm keen to develop my Rust-fu, but I'm not sure when time constraints would allow, so thought I'd at least open an issue for visibility

EDIT: not so sure about the necessity for this anymore, as providing the fallback in the CSS file renders the correct styles in Gmail anyways. I'm gonna close this, as it seems to be a lot of complexity where CSS has already provided a working solution

**Comment by jarshwah** [comment]
Can we reopen this one please? Translating would be super useful since most clients do not support css variables https://www.caniemail.com/search/?s=css+variables

Fallbacks are not enough when you depend on specific colours and fonts being used.

**Comment by larrybotha** [comment]
@jarshwah does PostCSS's [CSS Variables](https://github.com/MadLittleMods/postcss-css-variables#readme) help, here? They way I realised to use `css-inline` was to treat it as a tool that processes CSS as-is rather than something that I expect to be able to perform transformations on - it's up to the user to perform any transformations before `css-inline` evaluates anything

**Comment by jarshwah** [comment]
Thanks for pointing that out, but we don't have javascript in our pipeline at all, so unfortunately won't help us here. What we've ended up doing is using template tags (django templates) to render the actual values we want based on some inputs.
