### ISSUE TITLE
MJS export for npm module

### ISSUE THREAD

**Issue by harlan-zw** [Stranger6667/css-inline#260]
Hey, thanks for your work on css-inline! 

I'm using it in [nuxt-og-image](https://github.com/harlan-zw/nuxt-og-image) and having some issues with the CJS export of the code. Would it be possible to make a MJS export?

I'd be happy to provide a PR but I can't seem to see the js binding in the GitHub repo.

**Comment by Stranger6667** [comment]
Hi @harlan-zw!

Thank you for the report and your warm words! :) I am open to making this export, sure!

The bindings are located in the [bindings/wasm](https://github.com/Stranger6667/css-inline/tree/master/bindings/wasm) directory. I am not very experienced with JS, but I guess that the change might go to [this block](https://github.com/Stranger6667/css-inline/blob/master/bindings/wasm/src/lib.rs#L128). I'd appreciate any extra context you can provide :)

**Comment by harlan-zw** [comment]
Hm I don't know any rust but this doesn't seem to resemble the code that is within the `npm` package.

Is this rust code generating the block here https://unpkg.com/browse/css-inline@0.11.0/css_inline.js#L388?

See https://github.com/harlan-zw/nuxt-og-image/issues/93#issuecomment-1751680871 for extra context.

**Comment by DanSnow** [comment]
Hi @Stranger6667 ,

I think you can give `wasm-pack` a try. You can use `wasm-pack build --target bundler` to generate code that's more compatible with Nuxt.

https://rustwasm.github.io/docs/wasm-pack/commands/build.html

**Comment by Stranger6667** [comment]
Yep, currently the release build targets nodejs

**Comment by Stranger6667** [comment]
I am open to packaging it with `bundler` - can you verify that it will indeed work as expected in `nuxt-og-image`? Also, I am wondering what would be the best practice for node compatibility? I think I remember a few packages suffixed with `-node`, but not sure what is the most common approach - I am also not sure if we can package for these two styles simultaneously

**Comment by Stranger6667** [comment]
Bumping this issue - folks, let me know what would be the best way to solve this issue. I am open to releasing e.g. `css-inline-node` if needed.

**Comment by harlan-zw** [comment]
> I am open to packaging it with `bundler` - can you verify that it will indeed work as expected in `nuxt-og-image`? Also, I am wondering what would be the best practice for node compatibility? I think I remember a few packages suffixed with `-node`, but not sure what is the most common approach - I am also not sure if we can package for these two styles simultaneously

I can't know for sure until there's a version to try, unfortunately, I don't have much experience with `wasm-pack` and what it produces. Knowing that other WASM's are using this strategy it seems likely it would solve the problem.

If the rust isn't generating javascript with any specific node internals used `i.e require('fs')`, then I don't see any value in a node-specific package. A CJS and MJS export should cover all implementations, in theory. If it is, then I think you need to generate `NAPI` binaries as well? Seems like a hassle.

I'm happy to experiment if you want to publish under another package name or a beta flag for the time being.

**Comment by Stranger6667** [comment]
I really like what is done in `resvg-js` and given that `css-inline` has a much smaller API surface, I am going to experiment with `napi` & setup for wasm similar to what they have.

**Comment by Stranger6667** [comment]
The new bindings are implemented 🎉 There is a memory-optimized WASM module and regular `napi` bindings for platforms I was able to run the tests on. They will be available as `@css-inline/css-inline-wasm` and `@css-inline/css-inline` respectively. I am going to make releases for other languages and then will make one for JS as `0.12.0`. Meanwhile, [WASM package](https://github.com/Stranger6667/css-inline/tree/master/bindings/javascript/wasm) is available in the repo (with a public playground), but it is roughly 2x slower than `napi` bindings.

**Comment by Stranger6667** [comment]
So, similar to `resvg-js`, I published [napi bindings](https://www.npmjs.com/package/@css-inline/css-inline) and a WASM module. Hopefully, it solves the MJS issue, and `nuxt-og-image` can use these new bindings instead :)

**Comment by harlan-zw** [comment]
https://github.com/harlan-zw/nuxt-og-image/issues/119#issuecomment-1875530772 :tada:

**Comment by Stranger6667** [comment]
Awesome!
