### ISSUE TITLE
WASM Exception Thrown In 0.13.0

### ISSUE THREAD

**Issue by harlan-zw** [Stranger6667/css-inline#330]
When loading in the WASM file I get this error:

> [LinkError: WebAssembly.instantiate(): Import #9 module="wbg" function="__wbg_isSafeInteger_d8c89788832a17bf" error: function import requires a callable]

This seems to only be in an issue in 0.13.0, it's working correctly in 0.12.1.

Let me know if you need a reproduction, thanks for the help! :)

**Comment by Stranger6667** [comment]
Hi! Thanks for reporting, a repro would definitely help - the tests in this repo use exactly the same WASM module as in the release CI build, so I am wondering why they didn't catch the issue :)

**Comment by harlan-zw** [comment]
Not too sure, 0.13.1 seems to be working for the moment :shrug: I'll re-open with a reproduction if it pops up again.
