### ISSUE TITLE
Error: Cannot resolve "./css-inline.android-arm-eabi.node"

### ISSUE THREAD

**Issue by plexus77** [Stranger6667/css-inline#336]
Hi there,  I am building a nuxt 3 project on netlify using the netlify_edge preset and the build is failing as the android arm binding doesn't seem to be present in your repo.

**Comment by Stranger6667** [comment]
Hi! Thanks for reporting!

It looks like `index.js` includes some platforms that we don't have builds for. I'll take a look

**Comment by plexus77** [comment]
I am using the Nuxt SEO package and the [OG Image](https://nuxtseo.com/og-image/releases/v3) component uses your package.  I have removed it for now.
