### ISSUE TITLE
Keep npm published versions up to date

### ISSUE THREAD

**Issue by jlarmstrongiv** [Stranger6667/css-inline#353]
I’d like to use the new https://github.com/Stranger6667/css-inline/issues/265 feature for [dark mode](https://htmlemail.io/blog/dark-mode-email-styles) email media query styles, but npm is on `0.11.2` while github releases is on `0.13.1`

**Comment by Stranger6667** [comment]
The package migrated to `@css-inline/css-inline`, probably I need to add some migration guide or visible note on that. or maybe update that old package with a note

**Comment by Stranger6667** [comment]
![image](https://github.com/Stranger6667/css-inline/assets/1236561/02215eb5-8879-4994-a5db-f126962517b8)

Added a deprecation message, hopefully it could help to avoid confusion.

**Comment by jlarmstrongiv** [comment]
Perfect!  Thank you @Stranger6667
