### ISSUE TITLE
Can't find module for Windows 11 Arm JavaScript

### ISSUE THREAD

**Issue by gumilmo** [Stranger6667/css-inline#397]
Hello everyone!
I use the nestjs library **@nest-modules/mailer^2.0.2** which uses **@css-inline/css-inline 0.14.1**. When building the project I get the following error

```js
node_modules\@css-inline\css-inline\index.js:250
    throw loadError
    ^

Error: Cannot find module '@css-inline/css-inline-win32-arm64-msvc'
```

There is no package for Windows 11 arm? I tried to find and install the dependency manually, but to no avail.

**Comment by Stranger6667** [comment]
Hi! Thank you for opening this issue :)

The platform is missing right now, but I don't think it is an issue to add it, similar to [this one](https://github.com/Stranger6667/css-inline/blob/master/bindings/javascript/npm/win32-x64-msvc/package.json)

**Comment by 18259669383** [comment]
I had the same problem，But it doesn't seem to work out

> Hi! Thank you for opening this issue :)
> 
> The platform is missing right now, but I don't think it is an issue to add it, similar to [this one](https://github.com/Stranger6667/css-inline/blob/master/bindings/javascript/npm/win32-x64-msvc/package.json)

I had the same problem，But it doesn't seem to work out

**Comment by 18259669383** [comment]
> Hi! Thank you for opening this issue :)
> 
> The platform is missing right now, but I don't think it is an issue to add it, similar to [this one](https://github.com/Stranger6667/css-inline/blob/master/bindings/javascript/npm/win32-x64-msvc/package.json)

![图片](https://github.com/user-attachments/assets/8acf3a2f-56d9-447a-b470-ee1f7ad009c3)
![图片](https://github.com/user-attachments/assets/79c18985-e30e-4ea3-a0a0-660bfeb7086a)
