### ISSUE TITLE
Optionally ignore style tags in HTML, accept additional argument for css to inline?

### ISSUE THREAD

**Issue by cheapsteak** [Stranger6667/css-inline#45]
👋 Hi there :) 

Have you considered allowing css to inline be passed as an additional parameter?

(This might be related to https://github.com/Stranger6667/css-inline/issues/10 , but not quite the same)

The use case I'm thinking of is to possibly replace juice in mjml (I'm not affiliated, just a lib user), where css specified in `<mj-style inline="inline">` is collected as a separate string that's currently passed into juice as `extraCss`, and inlining of other css is disabled (which makes sense because sometimes you do want to tell clients that respect style sheets to do something different from outlook)

https://github.com/mjmlio/mjml/blob/246df840f4d0fcd812e51ca55bd6bef6592cb0e6/packages/mjml-core/src/index.js#L317-L319

**Comment by Stranger6667** [comment]
Hi @cheapsteak !

I didn't think about it, but having such a feature seems perfectly reasonable to me :) Correct me if I am wrong, but to support your use case, it might be:
- A `InlineOptions` option to disable "style" tag inlining;
- A `InlineOptions` option with extra CSS to inline;

As far as I see, the extra CSS should be in the form of qualified rules as a single string, e.g. `h1 {color: green}`, is it in this way in `mjml`? 
Also, from looking at the code sample you mentioned I am not sure what `insertPreservedExtraCss` option does? Could you, please, help me with that?

If the things above make sense, then I can implement that :) And I will appreciate if you can provide some input, expected output samples so I can include them to the test suite :)

Cheers

**Comment by cheapsteak** [comment]
> A InlineOptions option to disable "style" tag inlining;
> A InlineOptions option with extra CSS to inline;

yes that should work!

> the extra CSS should be in the form of qualified rules as a single string, e.g. h1 {color: green}, is it in this way in mjml?

yup! 

> insertPreservedExtraCss

that's a ["juice" parameter ](https://github.com/Automattic/juice/blob/master/README.md), i'll copy their description here :) 

>whether to insert into the document any preserved `@media` or `@font-face` content from `extraCss` when using `preserveMediaQueries`, `preserveFontFaces` or `preserveKeyFrames`. When `true` order of preference to append the `<style>` element is into `head`, then `body`, then at the end of the document. When a `string` the value is treated as a CSS/jQuery/cheerio selector, and when found, the `<style>` tag will be appended to the end of the first match. Defaults to `true`.

for emails, anything that can't be inlined should probably be thrown away, which I guess is why mjml had disabled that :)

**Comment by Stranger6667** [comment]
Thanks! I implemented the abovementioned options - `inline_style_tags` & `extra_css` (in #46 and #48 ). Is there anything else I can do regarding this feature?

I think that a new release could be issued when #49 is done so you can directly use it as a replacement for `juice` :) What do you think?

**Comment by cheapsteak** [comment]
those look awesome!!! please feel free to close this issue :)
