### ISSUE TITLE
Automate WASM release

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#55]
I need an npm account

https://developer.mozilla.org/en-US/docs/WebAssembly/Rust_to_wasm

**Comment by Stranger6667** [comment]
Hi @cheapsteak ! I released WASM package [here](https://www.npmjs.com/package/@stranger6667/css-inline-wasm) but I am not sure if it is missing some important parts (e.g. some metadata, but docs for sure). I'd be very grateful if you could check if the released package works for you :) And in general, I'll appreciate any feedback

I tested it here via some wasm-bindgen tests and some TypeScript [tests](https://github.com/Stranger6667/css-inline/blob/master/wasm/tests-ts/css_inline.spec.ts)

**Comment by cheapsteak** [comment]
Hi! 

I'm getting the following error trying to use this (made a temp repo for testing here https://github.com/cheapsteak/temp-test-css-inline)  

```
ERROR in ./node_modules/@stranger6667/css-inline-wasm/css_inline.js
Module not found: Error: Can't resolve './css_inline_bg.js' in '/Users/chang/projects/temp/test-css-inline/node_modules/@stranger6667/css-inline-wasm'
 @ ./node_modules/@stranger6667/css-inline-wasm/css_inline.js 2:0-35 2:0-35
 @ ./index.js

ERROR in ./node_modules/@stranger6667/css-inline-wasm/css_inline_bg.wasm
Module not found: Error: Can't resolve './css_inline_bg.js' in '/Users/chang/projects/temp/test-css-inline/node_modules/@stranger6667/css-inline-wasm'
 @ ./node_modules/@stranger6667/css-inline-wasm/css_inline_bg.wasm
 @ ./node_modules/@stranger6667/css-inline-wasm/css_inline.js
 @ ./index.js
ℹ ｢wdm｣: Failed to compile.
```

It looks like the pkg/package.json that gets generate isn't including `css_inline_bg.js` as part of the `files` that get included in the publish, and since `css_inline.js` depends on it, it errors

I tried manually adding that file into the package.json and publishing, and that does seem to work  

Wonder how that can be done automatically?

**Comment by Stranger6667** [comment]
Aha, thank you for the catch! It seems like the only automatic way to generate `package.json` with `css_inline_bg.js` is to put `--target nodejs` option to `wasm-pack build`. [Here](https://rustwasm.github.io/wasm-pack/book/commands/build.html#target) is some docs. Is target ok? If yes, then I can release a new version with this change

**Comment by cheapsteak** [comment]
Weird! Yeah let's try that  

Still confusing though
With the way that package.json and css_inline.js is generated, I can't imagine that would work against any platform? It's trying to import a file that doesn't exist since it wasn't included in the publish

**Comment by Stranger6667** [comment]
> With the way that package.json and css_inline.js is currently generated, I can't imagine that would work against any target?

Indeed! Probably worth reporting upstream. I'll try to play with it some more, but currently I published 0.4.1, which doesn't actually contain `css_inline_bg.js`, but `package.json` contains this filename

**Comment by Stranger6667** [comment]
Seems like this is already reported [here](https://github.com/rustwasm/wasm-pack/issues/866)

**Comment by Stranger6667** [comment]
I'll prepare a workaround tomorrow

**Comment by cheapsteak** [comment]
confirmed 0.4.1 works great 🙌
