### ISSUE TITLE
bug: Conditional html comments shouldn't be removed

### ISSUE THREAD

**Issue by cheapsteak** [Stranger6667/css-inline#64]
Conditional comments like `<!--[if mso]>Hello outlook<![endif]-->` and `<!--[if !mso]><!--><h1>Hello not outlook</h1><!--<![endif]-->` are used to either hide things from outlook or only show things to outlook, it looks like those are currently being stripped out

I have a failing test written on [this branch](https://github.com/Stranger6667/css-inline/compare/master...cheapsteak:chang/20/07/conditional-comments-test?expand=1))

Not sure where the problem is; I see code in kuchiki that [references comment nodes](https://github.com/kuchiki-rs/kuchiki/search?q=comment&unscoped_q=comment); this repo seems to be using the newest version, is it possibly a bug on kuchiki?

**Comment by Stranger6667** [comment]
Thank you for reporting this!

I ran the test you provided (btw, thank you for writing a failing test case!):

```
failures:

---- do_not_remove_conditional_comments stdout ----
thread 'do_not_remove_conditional_comments' panicked at 'assertion failed: `(left == right)`
  left: `"<html><head></head><!--[if mso]>Hello outlook<![endif]--><!--[if !mso]><!--><body><h1>Hello not outlook</h1><!--<![endif]--></body></html>"`,
 right: `"<html><head></head><!--[if mso]>Hello outlook<![endif]--><!--[if !mso]><!--><h1>Hello not outlook</h1><!--<![endif]--></html>"`', tests/test_inlining.rs:136:5
```

So, the only difference here is the "body" tag, the conditional tags in the input example are children of the "html" element and are preserved. However, the body start/end tags are unconditionally added to the tree and it mangles the original tree structure. I assume that the `html5ever` crate (which is used under the hood in `kuchiki`) considers this case as an invalid tree and add "body"  start/end tags to the tree during serialization or during the initial parsing. 

I don't remember exactly, but I observed similar behavior in Python's `lxml` library and it might come from some part of the HTML [spec](https://dom.spec.whatwg.org/), e.g. in [this example](https://html.spec.whatwg.org/multipage/parsing.html#unclosed-formatting-elements) there are no "html" or "body" tags, but the parsing result appears to have them anyway, I'll dig some more into this direction, but my current assumption is that this is the default parser behavior, which is probably described somewhere [here](https://html.spec.whatwg.org/multipage/parsing.html)

Also, if there is a body tag, then the final output stays the same (please, correct me if it is a valid case at all):
```html
<html>
   <head></head>
   <body>
      <!--[if mso]>Hello outlook<![endif]--><!--[if !mso]><!-->
      <h1>Hello not outlook</h1>
      <!--<![endif]-->
   </body>
</html>
```

Let me know what do you think :) Is it common to have these comments as children of the "html" element? Or is it more likely to have them inside head / body?

**Comment by cheapsteak** [comment]
oops! yes you're right my test was flawed  

I was experimenting with swapping out juice with css-inline-wasm and found quite a few [sections were being removed](https://user-images.githubusercontent.com/743976/87558077-aa1a7780-c686-11ea-95cc-72678dd55eb5.png), I thought the conditional comments were the culprit but you're right that definitely isn't why  

I'll see if I can isolate what is causing the issue then :)

**Comment by Stranger6667** [comment]
I'd be happy to know if `css-inline-wasm` fits your needs and if we can improve it :)

> I'll see if I can isolate what is causing the issue then :)

Let me know if I can help you with that somehow :)

**Comment by cheapsteak** [comment]
Was pure user error 😅  

In part of my attempt to swap out juice with css-inline-wasm, I accidentally removed mjml's default skeleton wrapper (html/head/body stuff)
Since kuchiki (unbeknownst to me at the time) added the necessary html/head/body tags to make the html valid again, I didn't realize that error and mistook this as css-inliner or kuchiki stripping things out
Adding back the default skeleton fixed everything!

Apologies again and thanks as always for your patient guidance 🙇 

---

(also btw it looks like removing the http feature/dependency cuts the wasm file down to 850447 bytes (down from 1491585) which is fairly significant)

**Comment by Stranger6667** [comment]
Thank you for the details! :)

> Apologies again and thanks as always for your patient guidance 

You are very welcome! :)

> (also btw it looks like removing the http feature/dependency cuts the wasm file down to 850447 bytes (down from 1491585) which is fairly significant)

I created #66 to track options for size reduction. I am not sure about the performance cost though, we can continue the discussion there - I am keen to know how much performance those tricks will cost and what we can actually tune more
