### ISSUE TITLE
Optimize WASM package size

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#66]
The current size: 1492887 bytes

How much we can cut off:
- `wasm-opt = ['-Os']` - 6629 bytes
- `wasm-opt = ['-Oz']` - 6763 bytes
- `opt-level = "s"` - 338471 bytes
- `opt-level = "z"` - 442795 bytes

So, the best I could get with the options above combined is a reduction by 447844 bytes in cost of some performance

Options I didn't try on my machine yet:
- Making HTTP loading conditional (e.g. via a feature flag + compile a separate package) should be around 640 Kb
- Smaller allocator, ~10kb

**Comment by Stranger6667** [comment]
I plan to replace the library for HTML handling, it might affect the size as well, then will take a look at conditional HTTP handling

**Comment by Stranger6667** [comment]
cc @cheapsteak 

Npm shows the following:

`Unpacked Size 860 kB` which is ~59% of the original size

Hope that helps :)

**Comment by cheapsteak** [comment]
whoooaa nice!!

**Comment by Stranger6667** [comment]
It might have a lower performance, but I plan to use `lol-html` instead of `kuchiki` which might yield 2-3x improvements, so I think that performance decrease will be vastly compensated by this libraries switch
