### ISSUE TITLE
Use `Cow` for parse error text

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/css-inline#76]
Sometimes they are static strings

**Comment by ChiefMilesEdgeworth** [comment]
I'd like to take this up. Looks pretty straightfoward. Anything I need to worry about?

**Comment by Stranger6667** [comment]
Hi @ChiefMilesEdgeworth !

Thank you! :) I think it should be only changing the `InlineError` variant to `ParseError(Cow<'a, str>)` and then adding `Cow` in all usage places. No extra troubles expected

**Comment by Stranger6667** [comment]
And maybe a few lifetime annotations (since `InlineError` needs it due to `Cow` usage)
